-- CREACION DE UN ESQUEMA FORMA SIMPLE

-- Paso 1: Crear el usuario: ALMACEN

create user ALMACEN
identified by admin;


-- Paso 2: Privilegios para el usuario ALMACEN

grant connect, resource to ALMACEN;

ALTER USER ALMACEN 
DEFAULT TABLESPACE USERS 
QUOTA UNLIMITED ON USERS;


-- Paso 3: Crear una tabla en ALMACEN

CREATE TABLE ALMACEN.PRODUCTO(
  ID NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  PRECIO NUMBER(10,2) NOT NULL,
  CONSTRAINT PK_PRODUCTO PRIMARY KEY( ID ),
  CONSTRAINT CK_PRODUCTO_PRECIO CHECK(PRECIO>=0)
);

CREATE SEQUENCE ALMACEN.SQ_ALMACEN;

INSERT INTO ALMACEN.PRODUCTO(ID,NOMBRE,PRECIO) 
VALUES(ALMACEN.SQ_ALMACEN.NEXTVAL,'TELEVISOR',4500.0);

COMMIT;

SELECT * FROM ALMACEN.PRODUCTO;

INSERT INTO ALMACEN.PRODUCTO(ID,NOMBRE,PRECIO) 
VALUES(ALMACEN.SQ_ALMACEN.NEXTVAL,'EQUIPO',500.0);

COMMIT;

SELECT * FROM ALMACEN.PRODUCTO;


-- Paso 4: Tabla VENTAS

CREATE TABLE ALMACEN.VENTAS(
  ID       NUMBER(10) NOT NULL,
  FECHA    DATE,
  CLIENTE  VARCHAR(100) NOT NULL,
  PROD_ID  NUMBER(10) NOT NULL,
  PRECIO   NUMBER(10,2) NOT NULL,
  CANTIDAD NUMBER(5) NOT NULL,
  IMPORTE  NUMBER(10,2) NOT NULL,
  CONSTRAINT PK_VENTA PRIMARY KEY( ID ),
  CONSTRAINT FK_VENTAS_PRODUCTO
             FOREIGN KEY( PROD_ID )
             REFERENCES ALMACEN.PRODUCTO,
  CONSTRAINT CK_VENTA_IMPORTE CHECK(IMPORTE>=0),
  CONSTRAINT CK_VENTA_VENTA CHECK(PRECIO * CANTIDAD = IMPORTE)
);

INSERT INTO ALMACEN.VENTAS(ID,FECHA,CLIENTE,PROD_ID,PRECIO,CANTIDAD,IMPORTE)
VALUES(1,SYSDATE,'GUSTAVO',1,1000,1,1000);

INSERT INTO ALMACEN.VENTAS(ID,FECHA,CLIENTE,PROD_ID,PRECIO,CANTIDAD,IMPORTE)
VALUES(2,SYSDATE,'GUSTAVO',3,1000,1,1000);

COMMIT;

SELECT * FROM ALMACEN.VENTAS;










